### ISSUE TITLE
Question: forcing phone code

### ISSUE THREAD

**Issue by olegafx** [halt-hammerzeit/input-format#1]
Thanks for your work, @halt-hammerzeit 

What's the best way to force a phone code inside of input-format? For example, `+7`.
`templateFormatter` with `+7 (xxx) xxx xx xx` appends `7` on every key press.

I guess that it should skip `+` as a first symbol and `7` as a second symbol. But it should append `+7` if `1-6` of `8-0` are entered.

**Comment by catamphetamine** [comment]
You didn't understand how the formatter works.
First the text input is parsed into `value`. It may be an empty string.
Then the value is formatted using the template.

So, for `1` digit being input the parsed `value` is `1`.
Then the `value` gets formatted using the template and outputs `+7 (1  )`.

Next, `2` digit is input.
The `value` is parsed: `+7 (12  )` -> `712`.
Then the `value` is formatted: `+7 (712)`.

So, the `template` isn't used for parsing – it's just used for formatting.
Write a custom `parse` function, it can do anything.
