### ISSUE TITLE
Integration with Angular 2 Webpack

### ISSUE THREAD

**Issue by rikhil9** [halt-hammerzeit/input-format#5]
How would integrate this library in Angular2/4 project.
Could you please provide steps for the same.

**Comment by catamphetamine** [comment]
There is `react input.js` component for React.
https://github.com/catamphetamine/input-format/blob/master/source/react%20input.js
I don't work with Angular so if anyone wants to add `angular input.js` component then see `react input.js` source code (which uses `input controller` under the hood).
