### ISSUE TITLE
Doesn't apply style object

### ISSUE THREAD

**Issue by abdifardin** [halt-hammerzeit/input-format#6]
I just tried this library with style props
But apparently it doesn't matter what props you pass, it just consider its default value

**Comment by catamphetamine** [comment]
Clarify your situation

**Comment by abdifardin** [comment]
Im using `react-phone-number-input` package.
Doing customization on <Phone ... > `inputStyle` doesn't works 

You are using `input-format` as an input, so the `inputStyle` will passed to the `input-format`
But it doesn't happen and when inspecting the code, i found the default style on the input

My real case is about to handle input error style 
If `is_valid_phone_number` return false, i want to make the input border and its color to red

I think you should add error handler props for `react-phone-number-input` as well 
I may send pull request for that :)

**Comment by catamphetamine** [comment]
I checked `inputStyle` and it works
