### ISSUE TITLE
Input pretty-print feature doesn't work for phone number without 0 at the beginning 

### ISSUE THREAD

**Issue by abdifardin** [halt-hammerzeit/input-format#7]
It would be great if you could support phone numbers without 0 at the beginning.
For example 

`09181233445`  = `9181233445` , it should be like this `0918 123 3445`
Whilst 
`09181233445` = `0918 123 3445`

**Comment by catamphetamine** [comment]
Can you provide a link to google's `libphonenumber` demo illustrating the desired result?

**Comment by catamphetamine** [comment]
Oh, and this library is not `libphonenumber-js`, perhaps you should have created this issue there.

**Comment by abdifardin** [comment]
If you can please try these two cases [here](http://catamphetamine.github.io/react-phone-number-input/) when Iraq is selected as country.

1. 7509863811
2. 07509863811 

The both cases are same so the input should be able to auto-space correctly 

Im writing here because i think `Input-format` package is formating the spaces between numbers

**Comment by catamphetamine** [comment]
> The both cases are same so the input should be able to auto-space correctly

Only if Google's libphonenumber library does the same.
Otherwise – not.

**Comment by catamphetamine** [comment]
If you think Google's libphonenumber behaves incorrectly then you can create an issue in their repo.

**Comment by catamphetamine** [comment]
This package has nothing to do with phone numbers.
It just receives a template in a form `xxx (xx) xx xxx` and a value `1234567890` and then formats it as `123 (45) 67 890`.

**Comment by abdifardin** [comment]
Yes ... i see 
Ok ... then you are formatting the input based on validation result from libphonenumber-js

**Comment by catamphetamine** [comment]
Yes, `libphonenumber-js` returns a `template` like `xxx (xx) xx xxx` and then this library formats the `value` using the template provided.

**Comment by abdifardin** [comment]
Ok thanks for your response.
I will create an issue with more details there
